-- -----------------------------------
-- 创建令牌权限表
-- -----------------------------------
CREATE TABLE "BLADEX"."BLADE_API_KEY"
(
    "ID" BIGINT NOT NULL,
    "TENANT_ID" VARCHAR(12) DEFAULT '000000',
    "USER_ID" BIGINT NOT NULL,
    "NAME" VARCHAR(128) NOT NULL,
    "API_KEY" VARCHAR(128) NOT NULL,
    "API_PATH" CLOB NULL,
    "EXPIRE_TIME" DATETIME NULL,
    "EXT_PARAMS" CLOB NULL,
    "CREATE_USER" BIGINT NULL,
    "CREATE_DEPT" BIGINT NULL,
    "CREATE_TIME" DATETIME NULL,
    "UPDATE_USER" BIGINT NULL,
    "UPDATE_TIME" DATETIME NULL,
    "STATUS" INT DEFAULT 1,
    "IS_DELETED" INT DEFAULT 0,
    PRIMARY KEY ("ID")
);

COMMENT ON TABLE "BLADEX"."BLADE_API_KEY" IS '令牌权限表';

COMMENT ON COLUMN "BLADEX"."BLADE_API_KEY"."ID" IS '主键';

COMMENT ON COLUMN "BLADEX"."BLADE_API_KEY"."TENANT_ID" IS '租户ID';

COMMENT ON COLUMN "BLADEX"."BLADE_API_KEY"."USER_ID" IS '用户ID';

COMMENT ON COLUMN "BLADEX"."BLADE_API_KEY"."NAME" IS '密钥名称';

COMMENT ON COLUMN "BLADEX"."BLADE_API_KEY"."API_KEY" IS 'API Key';

COMMENT ON COLUMN "BLADEX"."BLADE_API_KEY"."API_PATH" IS '访问权限';

COMMENT ON COLUMN "BLADEX"."BLADE_API_KEY"."EXPIRE_TIME" IS '过期时间';

COMMENT ON COLUMN "BLADEX"."BLADE_API_KEY"."EXT_PARAMS" IS '扩展参数(JSON)';

COMMENT ON COLUMN "BLADEX"."BLADE_API_KEY"."CREATE_USER" IS '创建人';

COMMENT ON COLUMN "BLADEX"."BLADE_API_KEY"."CREATE_DEPT" IS '创建部门';

COMMENT ON COLUMN "BLADEX"."BLADE_API_KEY"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "BLADEX"."BLADE_API_KEY"."UPDATE_USER" IS '修改人';

COMMENT ON COLUMN "BLADEX"."BLADE_API_KEY"."UPDATE_TIME" IS '修改时间';

COMMENT ON COLUMN "BLADEX"."BLADE_API_KEY"."STATUS" IS '状态';

COMMENT ON COLUMN "BLADEX"."BLADE_API_KEY"."IS_DELETED" IS '是否已删除';

-- -----------------------------------
-- 创建权限菜单
-- -----------------------------------
INSERT INTO "BLADEX"."BLADE_MENU" ("ID", "PARENT_ID", "CODE", "NAME", "ALIAS", "PATH", "SOURCE", "SORT", "CATEGORY", "ACTION", "IS_OPEN", "COMPONENT", "REMARK", "IS_DELETED") VALUES (1963598815738675311, 1123598815738675307, 'api_key', '令牌权限', 'menu', '/authority/apikey', 'iconfont icon-tianshenpi', 4, 1, 0, 1, '', NULL, 0);
INSERT INTO "BLADEX"."BLADE_MENU" ("ID", "PARENT_ID", "CODE", "NAME", "ALIAS", "PATH", "SOURCE", "SORT", "CATEGORY", "ACTION", "IS_OPEN", "COMPONENT", "REMARK", "IS_DELETED") VALUES (1963598815738675312, 1963598815738675311, 'api_key_setting', '权限配置', 'setting', NULL, 'setting', 1, 2, 2, 1, '', NULL, 0);

